## NumPy in Python

NumPy is a library of python which stands for Number Python 

In [ ]:
import time
import numpy as np

size = 100000

# add element of array a and b

def additon_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return (t2 - t1)  ## Time of the execution in normal python list

def addition_using_numpy():
    t1 = time.time();
    a = np.arange(size)
    b = np.arange(size)
    c = a + b         ## Easy to use and convenient compared to list. This is called vetorization
    t2 = time.time()
    return (t2 - t1)  ## Time of the execution in numpy array

t_list = additon_using_list()
t_numpy = addition_using_numpy()
print('List = ', t_list * 1000)  ## Millisecond
print('Numpy = ', t_numpy * 1000)  ##Milliseconds


## Numpy arrays required less memory and less time of execution compared to lists

In [13]:
import numpy as np

a = [1, 2, 3, 4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
a = [1, 2, 3, '5', 'a', 4.5]
b = np.array(a)
print(b)  ## ['1' '2' '3' '5' 'a' '4.5']

# np.array(array, datatype)
# np.array(array, dtype = int) ## by default dtype is string untill its mentioned

print(a*3)  ## [1, 2, 3, '5', 'a', 4.5, 1, 2, 3, '5', 'a', 4.5, 1, 2, 3, '5', 'a', 4.5]

['1' '2' '3' '5' 'a' '4.5']
[1, 2, 3, '5', 'a', 4.5, 1, 2, 3, '5', 'a', 4.5, 1, 2, 3, '5', 'a', 4.5]


In [18]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [19]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
b = np.zeros(4, dtype = int)
b

array([0, 0, 0, 0])

In [21]:
b = np.zeros((2, 3), dtype = int)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
b = np.full(3, 5, dtype = int)
b

array([5, 5, 5])

In [23]:
b = np.full((3, 3), 5, dtype = int)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
b = np.arange(10)  ## arange() function
print(b, "\n")
b = np.arange(2, 10)
print(b), "\n"
b = np.arange(2, 10, 2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [32]:
b = np.linspace(2, 10, dtype = int)  ## linspace() funtion
b

array([ 2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10])

In [33]:
b = np.identity(3)  ## has only one argument, size = n*n
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
b = np.eye(3) ## has two argument, size = m*n
print(b, "\n")
b = np.eye(3, 4)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [44]:
b = np.random.rand(4)
print(b, "\n")
b = np.random.rand(2, 3)
print(b, "\n")
b = np.random.rand(10)*10 ## this mutiplies every random number by 10, range is 0 - 10
print(b)

[0.82337612 0.27244331 0.51939776 0.18241885] 

[[0.916261   0.22082744 0.94209258]
 [0.04493732 0.45228048 0.10240599]] 

[7.94785934 3.88605567 6.91930232 6.65758124 8.82817036 7.25624664
 0.57247597 2.02812752 4.79207727 4.02795522]


In [46]:
import numpy as np

li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [47]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


In [51]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d, "\n")
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [55]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


In [ ]:
print(li_2d[1][:3])
print(li_2d)

In [65]:
b = [1, 2, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(b)
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())

[1 2 2 3 4 5 6 7 8 9]
47
4.7
1
9


In [71]:
li_1 = [1, 2, 3, 4, 5, 6, 7, 8]
li_2 = [9, 10, 11, 12, 13, 14, 15, 16]
a = np.array(li_1)
b = np.array(li_2)

c = a + b
print("c = ", c)
d = b - a
print("d = ", d)
e = b / a
print("e = ", e)
f = a * b
print("f = ", f)

c =  [10 12 14 16 18 20 22 24]
d =  [8 8 8 8 8 8 8 8]
e =  [9.         5.         3.66666667 3.         2.6        2.33333333
 2.14285714 2.        ]
f =  [  9  20  33  48  65  84 105 128]


In [76]:
a > b

array([False, False, False, False, False, False, False, False])

In [77]:
a == b

array([False, False, False, False, False, False, False, False])

In [78]:
a < b

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [80]:
a & b

array([1, 2, 3, 4, 5, 6, 7, 0])

In [81]:
a | b

array([ 9, 10, 11, 12, 13, 14, 15, 24])

In [82]:
new_arr = b[b>10]
new_arr

array([11, 12, 13, 14, 15, 16])

In [84]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([11, 12, 13, 14, 15, 16])

In [85]:
c = b
c[:3] = 19
c

array([19, 19, 19, 12, 13, 14, 15, 16])

In [87]:
c[c > 15] = 100
c

array([100, 100, 100,  12,  13,  14,  15, 100])

In [89]:
print(c[c == 100])

[100 100 100 100]


In [90]:
ind = np.where(c == 100)  ## where() tells the indexes where the value is present
ind

(array([0, 1, 2, 7]),)